all: Euclid_s_Algorithm.exe  Difference_Array.exe  Dijkstra.exe  Euler_s_totient.exe  Ternary_Search.exe  SCC.exe  TEMPLATE.exe  CRT.exe  Floyd_Warshall.exe  Flood_fill.exe  Binary_Exponentiation.exe  Sparse_Table.exe  Z_function.exe  Merge_Sort.exe  Max_Heap.exe  Extended_Euclid_s_Algorithm.exe  FenwickTree.exe  Disjoint_Set_Union.exe  Binary_Search.exe  Binomial_Coefficient.exe  Floor_Sum.exe  Sieve_of_Eratosthenes.exe  DFS.exe  Segment_Tree_RMQ.exe  2D_Prefix_Sum.exe  Segment_Tree_Range_Sum.exe  Tree_diameter.exe  Binomial_Theorem.exe  Simple_Dijkstra.exe  Kadane_s_Algorithm.exe  KMP.exe  Min_Heap.exe  Kosaraju.exe  Edmond_Karp_MaxFlow.exe  Priority_Queue.exe  Factorize.exe  BFS.exe  Bellman_Ford_Shortest_Path.exe  MEX.exe  Counting_Sort.exe 
Euclid_s_Algorithm.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Euclid_s_Algorithm.cpp -o Euclid_s_Algorithm.exe
Difference_Array.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Difference_Array.cpp -o Difference_Array.exe
Dijkstra.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Dijkstra.cpp -o Dijkstra.exe
Euler_s_totient.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Euler_s_totient.cpp -o Euler_s_totient.exe
Ternary_Search.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Ternary_Search.cpp -o Ternary_Search.exe
SCC.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op SCC.cpp -o SCC.exe
TEMPLATE.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op TEMPLATE.cpp -o TEMPLATE.exe
CRT.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op CRT.cpp -o CRT.exe
Floyd_Warshall.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Floyd_Warshall.cpp -o Floyd_Warshall.exe
Flood_fill.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Flood_fill.cpp -o Flood_fill.exe
Binary_Exponentiation.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binary_Exponentiation.cpp -o Binary_Exponentiation.exe
Sparse_Table.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Sparse_Table.cpp -o Sparse_Table.exe
Z_function.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Z_function.cpp -o Z_function.exe
Merge_Sort.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Merge_Sort.cpp -o Merge_Sort.exe
Max_Heap.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Max_Heap.cpp -o Max_Heap.exe
Extended_Euclid_s_Algorithm.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Extended_Euclid_s_Algorithm.cpp -o Extended_Euclid_s_Algorithm.exe
FenwickTree.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op FenwickTree.cpp -o FenwickTree.exe
Disjoint_Set_Union.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Disjoint_Set_Union.cpp -o Disjoint_Set_Union.exe
Binary_Search.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binary_Search.cpp -o Binary_Search.exe
Binomial_Coefficient.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binomial_Coefficient.cpp -o Binomial_Coefficient.exe
Floor_Sum.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Floor_Sum.cpp -o Floor_Sum.exe
Sieve_of_Eratosthenes.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Sieve_of_Eratosthenes.cpp -o Sieve_of_Eratosthenes.exe
DFS.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op DFS.cpp -o DFS.exe
Segment_Tree_RMQ.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Segment_Tree_RMQ.cpp -o Segment_Tree_RMQ.exe
2D_Prefix_Sum.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op 2D_Prefix_Sum.cpp -o 2D_Prefix_Sum.exe
Segment_Tree_Range_Sum.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Segment_Tree_Range_Sum.cpp -o Segment_Tree_Range_Sum.exe
Tree_diameter.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Tree_diameter.cpp -o Tree_diameter.exe
Binomial_Theorem.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binomial_Theorem.cpp -o Binomial_Theorem.exe
Simple_Dijkstra.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Simple_Dijkstra.cpp -o Simple_Dijkstra.exe
Kadane_s_Algorithm.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Kadane_s_Algorithm.cpp -o Kadane_s_Algorithm.exe
KMP.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op KMP.cpp -o KMP.exe
Min_Heap.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Min_Heap.cpp -o Min_Heap.exe
Kosaraju.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Kosaraju.cpp -o Kosaraju.exe
Edmond_Karp_MaxFlow.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Edmond_Karp_MaxFlow.cpp -o Edmond_Karp_MaxFlow.exe
Priority_Queue.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Priority_Queue.cpp -o Priority_Queue.exe
Factorize.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Factorize.cpp -o Factorize.exe
BFS.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op BFS.cpp -o BFS.exe
Bellman_Ford_Shortest_Path.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Bellman_Ford_Shortest_Path.cpp -o Bellman_Ford_Shortest_Path.exe
MEX.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op MEX.cpp -o MEX.exe
Counting_Sort.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Counting_Sort.cpp -o Counting_Sort.exe

force:
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Euclid_s_Algorithm.cpp -o Euclid_s_Algorithm.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Difference_Array.cpp -o Difference_Array.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Dijkstra.cpp -o Dijkstra.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Euler_s_totient.cpp -o Euler_s_totient.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Ternary_Search.cpp -o Ternary_Search.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op SCC.cpp -o SCC.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op TEMPLATE.cpp -o TEMPLATE.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op CRT.cpp -o CRT.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Floyd_Warshall.cpp -o Floyd_Warshall.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Flood_fill.cpp -o Flood_fill.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binary_Exponentiation.cpp -o Binary_Exponentiation.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Sparse_Table.cpp -o Sparse_Table.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Z_function.cpp -o Z_function.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Merge_Sort.cpp -o Merge_Sort.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Max_Heap.cpp -o Max_Heap.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Extended_Euclid_s_Algorithm.cpp -o Extended_Euclid_s_Algorithm.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op FenwickTree.cpp -o FenwickTree.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Disjoint_Set_Union.cpp -o Disjoint_Set_Union.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binary_Search.cpp -o Binary_Search.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binomial_Coefficient.cpp -o Binomial_Coefficient.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Floor_Sum.cpp -o Floor_Sum.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Sieve_of_Eratosthenes.cpp -o Sieve_of_Eratosthenes.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op DFS.cpp -o DFS.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Segment_Tree_RMQ.cpp -o Segment_Tree_RMQ.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op 2D_Prefix_Sum.cpp -o 2D_Prefix_Sum.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Segment_Tree_Range_Sum.cpp -o Segment_Tree_Range_Sum.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Tree_diameter.cpp -o Tree_diameter.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binomial_Theorem.cpp -o Binomial_Theorem.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Simple_Dijkstra.cpp -o Simple_Dijkstra.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Kadane_s_Algorithm.cpp -o Kadane_s_Algorithm.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op KMP.cpp -o KMP.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Min_Heap.cpp -o Min_Heap.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Kosaraju.cpp -o Kosaraju.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Edmond_Karp_MaxFlow.cpp -o Edmond_Karp_MaxFlow.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Priority_Queue.cpp -o Priority_Queue.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Factorize.cpp -o Factorize.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op BFS.cpp -o BFS.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Bellman_Ford_Shortest_Path.cpp -o Bellman_Ford_Shortest_Path.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op MEX.cpp -o MEX.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Counting_Sort.cpp -o Counting_Sort.exe

fast: fEuclid_s_Algorithm.exe  fDifference_Array.exe  fDijkstra.exe  fEuler_s_totient.exe  fTernary_Search.exe  fSCC.exe  fTEMPLATE.exe  fCRT.exe  fFloyd_Warshall.exe  fFlood_fill.exe  fBinary_Exponentiation.exe  fSparse_Table.exe  fZ_function.exe  fMerge_Sort.exe  fMax_Heap.exe  fExtended_Euclid_s_Algorithm.exe  fFenwickTree.exe  fDisjoint_Set_Union.exe  fBinary_Search.exe  fBinomial_Coefficient.exe  fFloor_Sum.exe  fSieve_of_Eratosthenes.exe  fDFS.exe  fSegment_Tree_RMQ.exe  f2D_Prefix_Sum.exe  fSegment_Tree_Range_Sum.exe  fTree_diameter.exe  fBinomial_Theorem.exe  fSimple_Dijkstra.exe  fKadane_s_Algorithm.exe  fKMP.exe  fMin_Heap.exe  fKosaraju.exe  fEdmond_Karp_MaxFlow.exe  fPriority_Queue.exe  fFactorize.exe  fBFS.exe  fBellman_Ford_Shortest_Path.exe  fMEX.exe  fCounting_Sort.exe 
fEuclid_s_Algorithm.exe: 
	g++ --std=c++20 -O0 Euclid_s_Algorithm.cpp -o fEuclid_s_Algorithm.exe
fDifference_Array.exe: 
	g++ --std=c++20 -O0 Difference_Array.cpp -o fDifference_Array.exe
fDijkstra.exe: 
	g++ --std=c++20 -O0 Dijkstra.cpp -o fDijkstra.exe
fEuler_s_totient.exe: 
	g++ --std=c++20 -O0 Euler_s_totient.cpp -o fEuler_s_totient.exe
fTernary_Search.exe: 
	g++ --std=c++20 -O0 Ternary_Search.cpp -o fTernary_Search.exe
fSCC.exe: 
	g++ --std=c++20 -O0 SCC.cpp -o fSCC.exe
fTEMPLATE.exe: 
	g++ --std=c++20 -O0 TEMPLATE.cpp -o fTEMPLATE.exe
fCRT.exe: 
	g++ --std=c++20 -O0 CRT.cpp -o fCRT.exe
fFloyd_Warshall.exe: 
	g++ --std=c++20 -O0 Floyd_Warshall.cpp -o fFloyd_Warshall.exe
fFlood_fill.exe: 
	g++ --std=c++20 -O0 Flood_fill.cpp -o fFlood_fill.exe
fBinary_Exponentiation.exe: 
	g++ --std=c++20 -O0 Binary_Exponentiation.cpp -o fBinary_Exponentiation.exe
fSparse_Table.exe: 
	g++ --std=c++20 -O0 Sparse_Table.cpp -o fSparse_Table.exe
fZ_function.exe: 
	g++ --std=c++20 -O0 Z_function.cpp -o fZ_function.exe
fMerge_Sort.exe: 
	g++ --std=c++20 -O0 Merge_Sort.cpp -o fMerge_Sort.exe
fMax_Heap.exe: 
	g++ --std=c++20 -O0 Max_Heap.cpp -o fMax_Heap.exe
fExtended_Euclid_s_Algorithm.exe: 
	g++ --std=c++20 -O0 Extended_Euclid_s_Algorithm.cpp -o fExtended_Euclid_s_Algorithm.exe
fFenwickTree.exe: 
	g++ --std=c++20 -O0 FenwickTree.cpp -o fFenwickTree.exe
fDisjoint_Set_Union.exe: 
	g++ --std=c++20 -O0 Disjoint_Set_Union.cpp -o fDisjoint_Set_Union.exe
fBinary_Search.exe: 
	g++ --std=c++20 -O0 Binary_Search.cpp -o fBinary_Search.exe
fBinomial_Coefficient.exe: 
	g++ --std=c++20 -O0 Binomial_Coefficient.cpp -o fBinomial_Coefficient.exe
fFloor_Sum.exe: 
	g++ --std=c++20 -O0 Floor_Sum.cpp -o fFloor_Sum.exe
fSieve_of_Eratosthenes.exe: 
	g++ --std=c++20 -O0 Sieve_of_Eratosthenes.cpp -o fSieve_of_Eratosthenes.exe
fDFS.exe: 
	g++ --std=c++20 -O0 DFS.cpp -o fDFS.exe
fSegment_Tree_RMQ.exe: 
	g++ --std=c++20 -O0 Segment_Tree_RMQ.cpp -o fSegment_Tree_RMQ.exe
f2D_Prefix_Sum.exe: 
	g++ --std=c++20 -O0 2D_Prefix_Sum.cpp -o f2D_Prefix_Sum.exe
fSegment_Tree_Range_Sum.exe: 
	g++ --std=c++20 -O0 Segment_Tree_Range_Sum.cpp -o fSegment_Tree_Range_Sum.exe
fTree_diameter.exe: 
	g++ --std=c++20 -O0 Tree_diameter.cpp -o fTree_diameter.exe
fBinomial_Theorem.exe: 
	g++ --std=c++20 -O0 Binomial_Theorem.cpp -o fBinomial_Theorem.exe
fSimple_Dijkstra.exe: 
	g++ --std=c++20 -O0 Simple_Dijkstra.cpp -o fSimple_Dijkstra.exe
fKadane_s_Algorithm.exe: 
	g++ --std=c++20 -O0 Kadane_s_Algorithm.cpp -o fKadane_s_Algorithm.exe
fKMP.exe: 
	g++ --std=c++20 -O0 KMP.cpp -o fKMP.exe
fMin_Heap.exe: 
	g++ --std=c++20 -O0 Min_Heap.cpp -o fMin_Heap.exe
fKosaraju.exe: 
	g++ --std=c++20 -O0 Kosaraju.cpp -o fKosaraju.exe
fEdmond_Karp_MaxFlow.exe: 
	g++ --std=c++20 -O0 Edmond_Karp_MaxFlow.cpp -o fEdmond_Karp_MaxFlow.exe
fPriority_Queue.exe: 
	g++ --std=c++20 -O0 Priority_Queue.cpp -o fPriority_Queue.exe
fFactorize.exe: 
	g++ --std=c++20 -O0 Factorize.cpp -o fFactorize.exe
fBFS.exe: 
	g++ --std=c++20 -O0 BFS.cpp -o fBFS.exe
fBellman_Ford_Shortest_Path.exe: 
	g++ --std=c++20 -O0 Bellman_Ford_Shortest_Path.cpp -o fBellman_Ford_Shortest_Path.exe
fMEX.exe: 
	g++ --std=c++20 -O0 MEX.cpp -o fMEX.exe
fCounting_Sort.exe: 
	g++ --std=c++20 -O0 Counting_Sort.cpp -o fCounting_Sort.exe

asm: Euclid_s_Algorithm.s  Difference_Array.s  Dijkstra.s  Euler_s_totient.s  Ternary_Search.s  SCC.s  TEMPLATE.s  CRT.s  Floyd_Warshall.s  Flood_fill.s  Binary_Exponentiation.s  Sparse_Table.s  Z_function.s  Merge_Sort.s  Max_Heap.s  Extended_Euclid_s_Algorithm.s  FenwickTree.s  Disjoint_Set_Union.s  Binary_Search.s  Binomial_Coefficient.s  Floor_Sum.s  Sieve_of_Eratosthenes.s  DFS.s  Segment_Tree_RMQ.s  2D_Prefix_Sum.s  Segment_Tree_Range_Sum.s  Tree_diameter.s  Binomial_Theorem.s  Simple_Dijkstra.s  Kadane_s_Algorithm.s  KMP.s  Min_Heap.s  Kosaraju.s  Edmond_Karp_MaxFlow.s  Priority_Queue.s  Factorize.s  BFS.s  Bellman_Ford_Shortest_Path.s  MEX.s  Counting_Sort.s 
Euclid_s_Algorithm.s: 
	oa.sh Euclid_s_Algorithm
Difference_Array.s: 
	oa.sh Difference_Array
Dijkstra.s: 
	oa.sh Dijkstra
Euler_s_totient.s: 
	oa.sh Euler_s_totient
Ternary_Search.s: 
	oa.sh Ternary_Search
SCC.s: 
	oa.sh SCC
TEMPLATE.s: 
	oa.sh TEMPLATE
CRT.s: 
	oa.sh CRT
Floyd_Warshall.s: 
	oa.sh Floyd_Warshall
Flood_fill.s: 
	oa.sh Flood_fill
Binary_Exponentiation.s: 
	oa.sh Binary_Exponentiation
Sparse_Table.s: 
	oa.sh Sparse_Table
Z_function.s: 
	oa.sh Z_function
Merge_Sort.s: 
	oa.sh Merge_Sort
Max_Heap.s: 
	oa.sh Max_Heap
Extended_Euclid_s_Algorithm.s: 
	oa.sh Extended_Euclid_s_Algorithm
FenwickTree.s: 
	oa.sh FenwickTree
Disjoint_Set_Union.s: 
	oa.sh Disjoint_Set_Union
Binary_Search.s: 
	oa.sh Binary_Search
Binomial_Coefficient.s: 
	oa.sh Binomial_Coefficient
Floor_Sum.s: 
	oa.sh Floor_Sum
Sieve_of_Eratosthenes.s: 
	oa.sh Sieve_of_Eratosthenes
DFS.s: 
	oa.sh DFS
Segment_Tree_RMQ.s: 
	oa.sh Segment_Tree_RMQ
2D_Prefix_Sum.s: 
	oa.sh 2D_Prefix_Sum
Segment_Tree_Range_Sum.s: 
	oa.sh Segment_Tree_Range_Sum
Tree_diameter.s: 
	oa.sh Tree_diameter
Binomial_Theorem.s: 
	oa.sh Binomial_Theorem
Simple_Dijkstra.s: 
	oa.sh Simple_Dijkstra
Kadane_s_Algorithm.s: 
	oa.sh Kadane_s_Algorithm
KMP.s: 
	oa.sh KMP
Min_Heap.s: 
	oa.sh Min_Heap
Kosaraju.s: 
	oa.sh Kosaraju
Edmond_Karp_MaxFlow.s: 
	oa.sh Edmond_Karp_MaxFlow
Priority_Queue.s: 
	oa.sh Priority_Queue
Factorize.s: 
	oa.sh Factorize
BFS.s: 
	oa.sh BFS
Bellman_Ford_Shortest_Path.s: 
	oa.sh Bellman_Ford_Shortest_Path
MEX.s: 
	oa.sh MEX
Counting_Sort.s: 
	oa.sh Counting_Sort

asmf: asmfEuclid_s_Algorithm.s  asmfDifference_Array.s  asmfDijkstra.s  asmfEuler_s_totient.s  asmfTernary_Search.s  asmfSCC.s  asmfTEMPLATE.s  asmfCRT.s  asmfFloyd_Warshall.s  asmfFlood_fill.s  asmfBinary_Exponentiation.s  asmfSparse_Table.s  asmfZ_function.s  asmfMerge_Sort.s  asmfMax_Heap.s  asmfExtended_Euclid_s_Algorithm.s  asmfFenwickTree.s  asmfDisjoint_Set_Union.s  asmfBinary_Search.s  asmfBinomial_Coefficient.s  asmfFloor_Sum.s  asmfSieve_of_Eratosthenes.s  asmfDFS.s  asmfSegment_Tree_RMQ.s  asmf2D_Prefix_Sum.s  asmfSegment_Tree_Range_Sum.s  asmfTree_diameter.s  asmfBinomial_Theorem.s  asmfSimple_Dijkstra.s  asmfKadane_s_Algorithm.s  asmfKMP.s  asmfMin_Heap.s  asmfKosaraju.s  asmfEdmond_Karp_MaxFlow.s  asmfPriority_Queue.s  asmfFactorize.s  asmfBFS.s  asmfBellman_Ford_Shortest_Path.s  asmfMEX.s  asmfCounting_Sort.s 
asmfEuclid_s_Algorithm.s: 
	ofa.sh Euclid_s_Algorithm
asmfDifference_Array.s: 
	ofa.sh Difference_Array
asmfDijkstra.s: 
	ofa.sh Dijkstra
asmfEuler_s_totient.s: 
	ofa.sh Euler_s_totient
asmfTernary_Search.s: 
	ofa.sh Ternary_Search
asmfSCC.s: 
	ofa.sh SCC
asmfTEMPLATE.s: 
	ofa.sh TEMPLATE
asmfCRT.s: 
	ofa.sh CRT
asmfFloyd_Warshall.s: 
	ofa.sh Floyd_Warshall
asmfFlood_fill.s: 
	ofa.sh Flood_fill
asmfBinary_Exponentiation.s: 
	ofa.sh Binary_Exponentiation
asmfSparse_Table.s: 
	ofa.sh Sparse_Table
asmfZ_function.s: 
	ofa.sh Z_function
asmfMerge_Sort.s: 
	ofa.sh Merge_Sort
asmfMax_Heap.s: 
	ofa.sh Max_Heap
asmfExtended_Euclid_s_Algorithm.s: 
	ofa.sh Extended_Euclid_s_Algorithm
asmfFenwickTree.s: 
	ofa.sh FenwickTree
asmfDisjoint_Set_Union.s: 
	ofa.sh Disjoint_Set_Union
asmfBinary_Search.s: 
	ofa.sh Binary_Search
asmfBinomial_Coefficient.s: 
	ofa.sh Binomial_Coefficient
asmfFloor_Sum.s: 
	ofa.sh Floor_Sum
asmfSieve_of_Eratosthenes.s: 
	ofa.sh Sieve_of_Eratosthenes
asmfDFS.s: 
	ofa.sh DFS
asmfSegment_Tree_RMQ.s: 
	ofa.sh Segment_Tree_RMQ
asmf2D_Prefix_Sum.s: 
	ofa.sh 2D_Prefix_Sum
asmfSegment_Tree_Range_Sum.s: 
	ofa.sh Segment_Tree_Range_Sum
asmfTree_diameter.s: 
	ofa.sh Tree_diameter
asmfBinomial_Theorem.s: 
	ofa.sh Binomial_Theorem
asmfSimple_Dijkstra.s: 
	ofa.sh Simple_Dijkstra
asmfKadane_s_Algorithm.s: 
	ofa.sh Kadane_s_Algorithm
asmfKMP.s: 
	ofa.sh KMP
asmfMin_Heap.s: 
	ofa.sh Min_Heap
asmfKosaraju.s: 
	ofa.sh Kosaraju
asmfEdmond_Karp_MaxFlow.s: 
	ofa.sh Edmond_Karp_MaxFlow
asmfPriority_Queue.s: 
	ofa.sh Priority_Queue
asmfFactorize.s: 
	ofa.sh Factorize
asmfBFS.s: 
	ofa.sh BFS
asmfBellman_Ford_Shortest_Path.s: 
	ofa.sh Bellman_Ford_Shortest_Path
asmfMEX.s: 
	ofa.sh MEX
asmfCounting_Sort.s: 
	ofa.sh Counting_Sort

clean:
	rm *.exe
	rm *.s
