all: MEX.exe  Sieve_of_Eratosthenes.exe  Kosaraju.exe  BST.exe  Binomial_Theorem.exe  Merge_Sort.exe  Counting_Sort.exe  Euler_s_totient.exe  Difference_Array.exe  TEMPLATE.exe  Segment_Tree_Lazy_Propagation.exe  Euclid_s_Algorithm.exe  KMP.exe  Edmond_Karp_MaxFlow.exe  Binary_Exponentiation.exe  Z_function.exe  Max_Heap.exe  FenwickTree.exe  Min_Heap.exe  Ternary_Search.exe  CRT.exe  DFS.exe  Treap.exe  Segment_Tree_RMQ.exe  Avl.exe  Dijkstra.exe  SCC.exe  Factorize.exe  Red_Black_Tree.exe  Segment_Tree_Range_Sum.exe  Fibonacci_heap.exe  Floor_Sum.exe  2D_Prefix_Sum.exe  Flood_fill.exe  BFS.exe  Simple_Dijkstra.exe  Kadane_s_Algorithm.exe  Bellman_Ford_Shortest_Path.exe  Extended_Euclid_s_Algorithm.exe  Sparse_Table.exe  Disjoint_Set_Union.exe  Binary_Search.exe  Floyd_Warshall.exe  Tree_diameter.exe  Binomial_Coefficient.exe  Priority_Queue.exe 
MEX.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op MEX.cpp -o MEX.exe
Sieve_of_Eratosthenes.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Sieve_of_Eratosthenes.cpp -o Sieve_of_Eratosthenes.exe
Kosaraju.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Kosaraju.cpp -o Kosaraju.exe
BST.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op BST.cpp -o BST.exe
Binomial_Theorem.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binomial_Theorem.cpp -o Binomial_Theorem.exe
Merge_Sort.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Merge_Sort.cpp -o Merge_Sort.exe
Counting_Sort.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Counting_Sort.cpp -o Counting_Sort.exe
Euler_s_totient.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Euler_s_totient.cpp -o Euler_s_totient.exe
Difference_Array.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Difference_Array.cpp -o Difference_Array.exe
TEMPLATE.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op TEMPLATE.cpp -o TEMPLATE.exe
Segment_Tree_Lazy_Propagation.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Segment_Tree_Lazy_Propagation.cpp -o Segment_Tree_Lazy_Propagation.exe
Euclid_s_Algorithm.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Euclid_s_Algorithm.cpp -o Euclid_s_Algorithm.exe
KMP.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op KMP.cpp -o KMP.exe
Edmond_Karp_MaxFlow.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Edmond_Karp_MaxFlow.cpp -o Edmond_Karp_MaxFlow.exe
Binary_Exponentiation.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binary_Exponentiation.cpp -o Binary_Exponentiation.exe
Z_function.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Z_function.cpp -o Z_function.exe
Max_Heap.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Max_Heap.cpp -o Max_Heap.exe
FenwickTree.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op FenwickTree.cpp -o FenwickTree.exe
Min_Heap.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Min_Heap.cpp -o Min_Heap.exe
Ternary_Search.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Ternary_Search.cpp -o Ternary_Search.exe
CRT.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op CRT.cpp -o CRT.exe
DFS.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op DFS.cpp -o DFS.exe
Treap.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Treap.cpp -o Treap.exe
Segment_Tree_RMQ.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Segment_Tree_RMQ.cpp -o Segment_Tree_RMQ.exe
Avl.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Avl.cpp -o Avl.exe
Dijkstra.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Dijkstra.cpp -o Dijkstra.exe
SCC.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op SCC.cpp -o SCC.exe
Factorize.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Factorize.cpp -o Factorize.exe
Red_Black_Tree.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Red_Black_Tree.cpp -o Red_Black_Tree.exe
Segment_Tree_Range_Sum.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Segment_Tree_Range_Sum.cpp -o Segment_Tree_Range_Sum.exe
Fibonacci_heap.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Fibonacci_heap.cpp -o Fibonacci_heap.exe
Floor_Sum.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Floor_Sum.cpp -o Floor_Sum.exe
2D_Prefix_Sum.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op 2D_Prefix_Sum.cpp -o 2D_Prefix_Sum.exe
Flood_fill.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Flood_fill.cpp -o Flood_fill.exe
BFS.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op BFS.cpp -o BFS.exe
Simple_Dijkstra.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Simple_Dijkstra.cpp -o Simple_Dijkstra.exe
Kadane_s_Algorithm.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Kadane_s_Algorithm.cpp -o Kadane_s_Algorithm.exe
Bellman_Ford_Shortest_Path.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Bellman_Ford_Shortest_Path.cpp -o Bellman_Ford_Shortest_Path.exe
Extended_Euclid_s_Algorithm.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Extended_Euclid_s_Algorithm.cpp -o Extended_Euclid_s_Algorithm.exe
Sparse_Table.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Sparse_Table.cpp -o Sparse_Table.exe
Disjoint_Set_Union.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Disjoint_Set_Union.cpp -o Disjoint_Set_Union.exe
Binary_Search.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binary_Search.cpp -o Binary_Search.exe
Floyd_Warshall.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Floyd_Warshall.cpp -o Floyd_Warshall.exe
Tree_diameter.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Tree_diameter.cpp -o Tree_diameter.exe
Binomial_Coefficient.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binomial_Coefficient.cpp -o Binomial_Coefficient.exe
Priority_Queue.exe: 
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Priority_Queue.cpp -o Priority_Queue.exe

force:
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op MEX.cpp -o MEX.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Sieve_of_Eratosthenes.cpp -o Sieve_of_Eratosthenes.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Kosaraju.cpp -o Kosaraju.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op BST.cpp -o BST.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binomial_Theorem.cpp -o Binomial_Theorem.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Merge_Sort.cpp -o Merge_Sort.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Counting_Sort.cpp -o Counting_Sort.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Euler_s_totient.cpp -o Euler_s_totient.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Difference_Array.cpp -o Difference_Array.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op TEMPLATE.cpp -o TEMPLATE.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Segment_Tree_Lazy_Propagation.cpp -o Segment_Tree_Lazy_Propagation.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Euclid_s_Algorithm.cpp -o Euclid_s_Algorithm.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op KMP.cpp -o KMP.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Edmond_Karp_MaxFlow.cpp -o Edmond_Karp_MaxFlow.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binary_Exponentiation.cpp -o Binary_Exponentiation.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Z_function.cpp -o Z_function.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Max_Heap.cpp -o Max_Heap.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op FenwickTree.cpp -o FenwickTree.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Min_Heap.cpp -o Min_Heap.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Ternary_Search.cpp -o Ternary_Search.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op CRT.cpp -o CRT.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op DFS.cpp -o DFS.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Treap.cpp -o Treap.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Segment_Tree_RMQ.cpp -o Segment_Tree_RMQ.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Avl.cpp -o Avl.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Dijkstra.cpp -o Dijkstra.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op SCC.cpp -o SCC.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Factorize.cpp -o Factorize.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Red_Black_Tree.cpp -o Red_Black_Tree.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Segment_Tree_Range_Sum.cpp -o Segment_Tree_Range_Sum.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Fibonacci_heap.cpp -o Fibonacci_heap.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Floor_Sum.cpp -o Floor_Sum.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op 2D_Prefix_Sum.cpp -o 2D_Prefix_Sum.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Flood_fill.cpp -o Flood_fill.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op BFS.cpp -o BFS.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Simple_Dijkstra.cpp -o Simple_Dijkstra.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Kadane_s_Algorithm.cpp -o Kadane_s_Algorithm.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Bellman_Ford_Shortest_Path.cpp -o Bellman_Ford_Shortest_Path.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Extended_Euclid_s_Algorithm.cpp -o Extended_Euclid_s_Algorithm.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Sparse_Table.cpp -o Sparse_Table.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Disjoint_Set_Union.cpp -o Disjoint_Set_Union.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binary_Search.cpp -o Binary_Search.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Floyd_Warshall.cpp -o Floyd_Warshall.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Tree_diameter.cpp -o Tree_diameter.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Binomial_Coefficient.cpp -o Binomial_Coefficient.exe
	g++ -Wall -g --std=c++20 -static -Wextra -pedantic -O2 -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op Priority_Queue.cpp -o Priority_Queue.exe

fast: fMEX.exe  fSieve_of_Eratosthenes.exe  fKosaraju.exe  fBST.exe  fBinomial_Theorem.exe  fMerge_Sort.exe  fCounting_Sort.exe  fEuler_s_totient.exe  fDifference_Array.exe  fTEMPLATE.exe  fSegment_Tree_Lazy_Propagation.exe  fEuclid_s_Algorithm.exe  fKMP.exe  fEdmond_Karp_MaxFlow.exe  fBinary_Exponentiation.exe  fZ_function.exe  fMax_Heap.exe  fFenwickTree.exe  fMin_Heap.exe  fTernary_Search.exe  fCRT.exe  fDFS.exe  fTreap.exe  fSegment_Tree_RMQ.exe  fAvl.exe  fDijkstra.exe  fSCC.exe  fFactorize.exe  fRed_Black_Tree.exe  fSegment_Tree_Range_Sum.exe  fFibonacci_heap.exe  fFloor_Sum.exe  f2D_Prefix_Sum.exe  fFlood_fill.exe  fBFS.exe  fSimple_Dijkstra.exe  fKadane_s_Algorithm.exe  fBellman_Ford_Shortest_Path.exe  fExtended_Euclid_s_Algorithm.exe  fSparse_Table.exe  fDisjoint_Set_Union.exe  fBinary_Search.exe  fFloyd_Warshall.exe  fTree_diameter.exe  fBinomial_Coefficient.exe  fPriority_Queue.exe 
fMEX.exe: 
	g++ --std=c++20 -O0 MEX.cpp -o fMEX.exe
fSieve_of_Eratosthenes.exe: 
	g++ --std=c++20 -O0 Sieve_of_Eratosthenes.cpp -o fSieve_of_Eratosthenes.exe
fKosaraju.exe: 
	g++ --std=c++20 -O0 Kosaraju.cpp -o fKosaraju.exe
fBST.exe: 
	g++ --std=c++20 -O0 BST.cpp -o fBST.exe
fBinomial_Theorem.exe: 
	g++ --std=c++20 -O0 Binomial_Theorem.cpp -o fBinomial_Theorem.exe
fMerge_Sort.exe: 
	g++ --std=c++20 -O0 Merge_Sort.cpp -o fMerge_Sort.exe
fCounting_Sort.exe: 
	g++ --std=c++20 -O0 Counting_Sort.cpp -o fCounting_Sort.exe
fEuler_s_totient.exe: 
	g++ --std=c++20 -O0 Euler_s_totient.cpp -o fEuler_s_totient.exe
fDifference_Array.exe: 
	g++ --std=c++20 -O0 Difference_Array.cpp -o fDifference_Array.exe
fTEMPLATE.exe: 
	g++ --std=c++20 -O0 TEMPLATE.cpp -o fTEMPLATE.exe
fSegment_Tree_Lazy_Propagation.exe: 
	g++ --std=c++20 -O0 Segment_Tree_Lazy_Propagation.cpp -o fSegment_Tree_Lazy_Propagation.exe
fEuclid_s_Algorithm.exe: 
	g++ --std=c++20 -O0 Euclid_s_Algorithm.cpp -o fEuclid_s_Algorithm.exe
fKMP.exe: 
	g++ --std=c++20 -O0 KMP.cpp -o fKMP.exe
fEdmond_Karp_MaxFlow.exe: 
	g++ --std=c++20 -O0 Edmond_Karp_MaxFlow.cpp -o fEdmond_Karp_MaxFlow.exe
fBinary_Exponentiation.exe: 
	g++ --std=c++20 -O0 Binary_Exponentiation.cpp -o fBinary_Exponentiation.exe
fZ_function.exe: 
	g++ --std=c++20 -O0 Z_function.cpp -o fZ_function.exe
fMax_Heap.exe: 
	g++ --std=c++20 -O0 Max_Heap.cpp -o fMax_Heap.exe
fFenwickTree.exe: 
	g++ --std=c++20 -O0 FenwickTree.cpp -o fFenwickTree.exe
fMin_Heap.exe: 
	g++ --std=c++20 -O0 Min_Heap.cpp -o fMin_Heap.exe
fTernary_Search.exe: 
	g++ --std=c++20 -O0 Ternary_Search.cpp -o fTernary_Search.exe
fCRT.exe: 
	g++ --std=c++20 -O0 CRT.cpp -o fCRT.exe
fDFS.exe: 
	g++ --std=c++20 -O0 DFS.cpp -o fDFS.exe
fTreap.exe: 
	g++ --std=c++20 -O0 Treap.cpp -o fTreap.exe
fSegment_Tree_RMQ.exe: 
	g++ --std=c++20 -O0 Segment_Tree_RMQ.cpp -o fSegment_Tree_RMQ.exe
fAvl.exe: 
	g++ --std=c++20 -O0 Avl.cpp -o fAvl.exe
fDijkstra.exe: 
	g++ --std=c++20 -O0 Dijkstra.cpp -o fDijkstra.exe
fSCC.exe: 
	g++ --std=c++20 -O0 SCC.cpp -o fSCC.exe
fFactorize.exe: 
	g++ --std=c++20 -O0 Factorize.cpp -o fFactorize.exe
fRed_Black_Tree.exe: 
	g++ --std=c++20 -O0 Red_Black_Tree.cpp -o fRed_Black_Tree.exe
fSegment_Tree_Range_Sum.exe: 
	g++ --std=c++20 -O0 Segment_Tree_Range_Sum.cpp -o fSegment_Tree_Range_Sum.exe
fFibonacci_heap.exe: 
	g++ --std=c++20 -O0 Fibonacci_heap.cpp -o fFibonacci_heap.exe
fFloor_Sum.exe: 
	g++ --std=c++20 -O0 Floor_Sum.cpp -o fFloor_Sum.exe
f2D_Prefix_Sum.exe: 
	g++ --std=c++20 -O0 2D_Prefix_Sum.cpp -o f2D_Prefix_Sum.exe
fFlood_fill.exe: 
	g++ --std=c++20 -O0 Flood_fill.cpp -o fFlood_fill.exe
fBFS.exe: 
	g++ --std=c++20 -O0 BFS.cpp -o fBFS.exe
fSimple_Dijkstra.exe: 
	g++ --std=c++20 -O0 Simple_Dijkstra.cpp -o fSimple_Dijkstra.exe
fKadane_s_Algorithm.exe: 
	g++ --std=c++20 -O0 Kadane_s_Algorithm.cpp -o fKadane_s_Algorithm.exe
fBellman_Ford_Shortest_Path.exe: 
	g++ --std=c++20 -O0 Bellman_Ford_Shortest_Path.cpp -o fBellman_Ford_Shortest_Path.exe
fExtended_Euclid_s_Algorithm.exe: 
	g++ --std=c++20 -O0 Extended_Euclid_s_Algorithm.cpp -o fExtended_Euclid_s_Algorithm.exe
fSparse_Table.exe: 
	g++ --std=c++20 -O0 Sparse_Table.cpp -o fSparse_Table.exe
fDisjoint_Set_Union.exe: 
	g++ --std=c++20 -O0 Disjoint_Set_Union.cpp -o fDisjoint_Set_Union.exe
fBinary_Search.exe: 
	g++ --std=c++20 -O0 Binary_Search.cpp -o fBinary_Search.exe
fFloyd_Warshall.exe: 
	g++ --std=c++20 -O0 Floyd_Warshall.cpp -o fFloyd_Warshall.exe
fTree_diameter.exe: 
	g++ --std=c++20 -O0 Tree_diameter.cpp -o fTree_diameter.exe
fBinomial_Coefficient.exe: 
	g++ --std=c++20 -O0 Binomial_Coefficient.cpp -o fBinomial_Coefficient.exe
fPriority_Queue.exe: 
	g++ --std=c++20 -O0 Priority_Queue.cpp -o fPriority_Queue.exe

asm: MEX.s  Sieve_of_Eratosthenes.s  Kosaraju.s  BST.s  Binomial_Theorem.s  Merge_Sort.s  Counting_Sort.s  Euler_s_totient.s  Difference_Array.s  TEMPLATE.s  Segment_Tree_Lazy_Propagation.s  Euclid_s_Algorithm.s  KMP.s  Edmond_Karp_MaxFlow.s  Binary_Exponentiation.s  Z_function.s  Max_Heap.s  FenwickTree.s  Min_Heap.s  Ternary_Search.s  CRT.s  DFS.s  Treap.s  Segment_Tree_RMQ.s  Avl.s  Dijkstra.s  SCC.s  Factorize.s  Red_Black_Tree.s  Segment_Tree_Range_Sum.s  Fibonacci_heap.s  Floor_Sum.s  2D_Prefix_Sum.s  Flood_fill.s  BFS.s  Simple_Dijkstra.s  Kadane_s_Algorithm.s  Bellman_Ford_Shortest_Path.s  Extended_Euclid_s_Algorithm.s  Sparse_Table.s  Disjoint_Set_Union.s  Binary_Search.s  Floyd_Warshall.s  Tree_diameter.s  Binomial_Coefficient.s  Priority_Queue.s 
MEX.s: 
	oa.sh MEX
Sieve_of_Eratosthenes.s: 
	oa.sh Sieve_of_Eratosthenes
Kosaraju.s: 
	oa.sh Kosaraju
BST.s: 
	oa.sh BST
Binomial_Theorem.s: 
	oa.sh Binomial_Theorem
Merge_Sort.s: 
	oa.sh Merge_Sort
Counting_Sort.s: 
	oa.sh Counting_Sort
Euler_s_totient.s: 
	oa.sh Euler_s_totient
Difference_Array.s: 
	oa.sh Difference_Array
TEMPLATE.s: 
	oa.sh TEMPLATE
Segment_Tree_Lazy_Propagation.s: 
	oa.sh Segment_Tree_Lazy_Propagation
Euclid_s_Algorithm.s: 
	oa.sh Euclid_s_Algorithm
KMP.s: 
	oa.sh KMP
Edmond_Karp_MaxFlow.s: 
	oa.sh Edmond_Karp_MaxFlow
Binary_Exponentiation.s: 
	oa.sh Binary_Exponentiation
Z_function.s: 
	oa.sh Z_function
Max_Heap.s: 
	oa.sh Max_Heap
FenwickTree.s: 
	oa.sh FenwickTree
Min_Heap.s: 
	oa.sh Min_Heap
Ternary_Search.s: 
	oa.sh Ternary_Search
CRT.s: 
	oa.sh CRT
DFS.s: 
	oa.sh DFS
Treap.s: 
	oa.sh Treap
Segment_Tree_RMQ.s: 
	oa.sh Segment_Tree_RMQ
Avl.s: 
	oa.sh Avl
Dijkstra.s: 
	oa.sh Dijkstra
SCC.s: 
	oa.sh SCC
Factorize.s: 
	oa.sh Factorize
Red_Black_Tree.s: 
	oa.sh Red_Black_Tree
Segment_Tree_Range_Sum.s: 
	oa.sh Segment_Tree_Range_Sum
Fibonacci_heap.s: 
	oa.sh Fibonacci_heap
Floor_Sum.s: 
	oa.sh Floor_Sum
2D_Prefix_Sum.s: 
	oa.sh 2D_Prefix_Sum
Flood_fill.s: 
	oa.sh Flood_fill
BFS.s: 
	oa.sh BFS
Simple_Dijkstra.s: 
	oa.sh Simple_Dijkstra
Kadane_s_Algorithm.s: 
	oa.sh Kadane_s_Algorithm
Bellman_Ford_Shortest_Path.s: 
	oa.sh Bellman_Ford_Shortest_Path
Extended_Euclid_s_Algorithm.s: 
	oa.sh Extended_Euclid_s_Algorithm
Sparse_Table.s: 
	oa.sh Sparse_Table
Disjoint_Set_Union.s: 
	oa.sh Disjoint_Set_Union
Binary_Search.s: 
	oa.sh Binary_Search
Floyd_Warshall.s: 
	oa.sh Floyd_Warshall
Tree_diameter.s: 
	oa.sh Tree_diameter
Binomial_Coefficient.s: 
	oa.sh Binomial_Coefficient
Priority_Queue.s: 
	oa.sh Priority_Queue

clean:
	rm *.exe
